
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijmgsgoimoawcaawbrqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqbWdzZ29pbW9hd2NhYXdicnFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NTI0NTYsImV4cCI6MjA1OTMyODQ1Nn0.8j2Cy9c2Lwe5-Fk-5U2EAEMrElvdQvUZ-smbZWjUo90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
